version: "3.9"

services:
  web:
    build: .
    container_name: scooters_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "python scooters/manage.py migrate && python scooters/manage.py runserver 0.0.0.0:8000"
