# Generated by Django 5.2.7 on 2025-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')], max_length=15)),
                ('battery_level', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('per_minute', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
            ],
        ),
    ]
