# Generated by Django 5.2.7 on 2025-10-31 10:23

import django.db.models.deletion
import django.utils.timezone
import rental.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_scooter_battery_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=rental.models.reservation_default_expiry)),
                ('is_active', models.BooleanField(default=True)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rental.scooter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('scooter',), name='uniq_active_reservation_per_scooter'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_reservation_per_user')],
            },
        ),
    ]
