# Generated by Django 5.2.7 on 2025-10-31 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=15)),
                ('total_minutes', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rental.scooter')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rental.tariff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_rental_per_user'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('scooter',), name='uniq_active_rental_per_scooter')],
            },
        ),
    ]
